// Prints the generated part of the "Project gallery images" section of docs/redesign/asset-sources.md.
// Run: node scripts/gallery-credits.mjs
import { readFileSync } from "node:fs"
const manifest = JSON.parse(readFileSync(new URL("../lib/project-gallery.data.json", import.meta.url), "utf8"))
// Projects with no manifest images yet (see PENDING in lib/project-gallery.ts).
const PENDING = ["eukarya", "hackmate"]
const slugs = [...new Set([...Object.keys(manifest), ...PENDING])].sort((a, b) => (a === "eukarya" ? -1 : 0) - (b === "eukarya" ? -1 : 0) || 0)
const lines = ["> Generated by `node scripts/gallery-credits.mjs` from the manifest. Do not edit by hand; hand-written notes live under their own heading below.", ""]
for (const slug of slugs) {
  const images = manifest[slug] ?? []
  lines.push(`### ${slug}`, "")
  if (images.length === 0) lines.push("_Pending: no gallery images yet._")
  for (const image of images) {
    lines.push(`- \`public${image.src}\` (${image.width}×${image.height}): credit ${image.credit}; source ${image.source}${image.origin ? `; downloaded from ${image.origin}` : ""}.`)
  }
  lines.push("")
}
process.stdout.write(lines.join("\n"))
